name: fluttertop
title: FlutterTop
version: "0.1.0"
summary: A simple system monitor made with flutter for aesthetic visualization of system processes.
description: |
  FlutterTop is a powerful, visually stunning system monitoring dashboard for Linux.
  It tracks CPU, Memory, Disk, Network, and GPU usage in real-time with an emphasis on clarity and performance.

license: MIT
website: https://github.com/deepMind1234/fluttertop
contact: soulfulsapien@gmail.com
donation: https://github.com/deepMind1234/fluttertop#donations
issues: https://github.com/deepMind1234/fluttertop/issues
source-code: https://github.com/deepMind1234/fluttertop

confinement: strict
base: core24
grade: stable

# This tells Snapcraft where the desktop file and icon are.
# By convention, snap/gui/fluttertop.desktop and snap/gui/fluttertop.png are automatically copied.

apps:
  fluttertop:
    command: fluttertop
    extensions: [gnome]
    common-id: com.example.fluttertop
    plugs:
      - network
      - system-observe
      - hardware-observe
      - mount-observe
      - opengl
      - wayland
      - x11

parts:
  fluttertop:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - lld
      - llvm
      - binutils
